{application,pbkdf2_elixir,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto,comeonin]},
              {description,"pbkdf2_elixir"},
              {modules,['Elixir.Pbkdf2','Elixir.Pbkdf2.Base',
                        'Elixir.Pbkdf2.Base64','Elixir.Pbkdf2.Stats',
                        'Elixir.Pbkdf2.Tools']},
              {registered,[]},
              {vsn,"2.2.0"}]}.
